name: Java CI

on: [push]

jobs:
  Test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: sormuras/download-jdk@v1
        with:
          feature: Loom
      - uses: actions/checkout@v2
      - name: Install JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: temurin
      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: 'jdkfile'
          jdkFile: ${{ env.JDK_FILE }}
      - name: JVM
        run: java --version
      - name: Path
        run: bash -c 'echo $PATH'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify